--- #YAML:1.0
build_requires:
  Test::More: 0
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: Module::Build version 0.13
license: perl
name: poest
recommends:
  Config::General: 0
requires:
  POE: 0.25
  POE::Component::Server::SMTP: 0
  POE::Session::MultiDispatch: 0
  perl: 5.5.3
version: 0.20030322
